service: spark-joy

provider:
    name: aws
    runtime: nodejs8.10
    stage: dev
    region: us-west-2


functions:
    graphql:
        handler: dist/graphql.handler
        events:
            - http:
                  path: graphql
                  method: GET
                  cors: true
